# SPDX-License-Identifier: GPL-3.0-only
# minColorAE. Copyright (C) 2026 cbkow. Part of a work derived from OpenDRT v1.1.0 by Jed Smith (GPLv3); see NOTICE.
# Embed one or more text files, concatenated, as a C raw string constant, at build time.
#   cmake -DIN=<src1;src2;...> -DOUT=<header> -DNAME=<identifier> -P embed_text.cmake
# Used for shader sources the effects compile at run time: Metal has no include
# path for newLibraryWithSource:, so the shim, the params, the kernel and the
# host wrapper are pasted into one string in that order. The text ships inside
# the plugin binary and can never drift from the build that loaded it.
if(NOT IN OR NOT OUT OR NOT NAME)
  message(FATAL_ERROR "embed_text.cmake needs -DIN -DOUT -DNAME")
endif()
set(_all "")
string(REPLACE "|" ";" IN "${IN}")   # several inputs arrive '|'-joined (a ';' list would split on the command line)
foreach(_f IN LISTS IN)
  file(READ "${_f}" _txt)
  string(FIND "${_txt}" ")DRTSRC\"" _clash)
  if(NOT _clash EQUAL -1)
    message(FATAL_ERROR "${_f} contains the raw-string terminator )DRTSRC\"")
  endif()
  get_filename_component(_n "${_f}" NAME)
  string(APPEND _all "\n/* ---- ${_n} ---- */\n${_txt}\n")
endforeach()
file(WRITE "${OUT}" "/* generated by embed_text.cmake from: ${IN}; do not edit */\nstatic const char ${NAME}[] = R\"DRTSRC(${_all})DRTSRC\";\n")
