// SPDX-License-Identifier: GPL-3.0-only
// minColorAE. Copyright (C) 2026 cbkow.
//
// minColor panel (ScriptUI). Workflow only: it adds the minColor effects and keeps
// the project's sidecar folder; nothing a frame renders depends on it, and every
// effect works the same without it.
//
// 100% manual: it never reads or reports the project's colour settings. AE's
// scripting answers for them (config name, working space) can be stale or wrong
// (a silent fallback keeps the old label), and minColor does no colour
// detection anyway. No timers, no idle work; it changes the project only from a
// button and reports only what that click did.
//
// Sidecar: <project folder>/minColor/ holds mincolor.ocio (the OCIO config),
// in.json (the In presets, written from the panel's starter on first use) and
// project.json (the working space Fix OCIO set, which Apply In and Add Output
// follow: the panel's own record, never read back from AE). Fix OCIO writes the
// config there, makes it the project's OCIO config, and sets the chosen working
// space by editing the saved .aep and reopening it: AE has no API that sets an
// OCIO working space (the scripting setter leaves it None, the plug-in suites are
// read-only), and on a config switch it keeps the old working-space name, or
// none. AE stores the config path absolutely, so after moving the project, press
// it again. Adobe-engine projects (working space None, footage on Preserve RGB)
// pass pixels through: there the Output encodes for the display and the macOS
// Fix effect, added by hand on a guide layer, corrects the viewer.
//
// ExtendScript groups an unparenthesised nested ?: from the LEFT; always parenthesise.
//
// The build fills the @...@ tokens (panel/CMakeLists.txt, embed.cmake): the version,
// the OCIO config, the starter in.json and the effects' menu entries, so what the
// panel writes and sets can never drift from the build it ships with.

(function (thisObj) {
 var LOG = ($.os.indexOf("Windows") >= 0 ? Folder.temp.fsName : "/tmp") + "/mincolor_panel.log";   /* %TEMP% on Windows; a throw while a panel loads is a modal dialog, so log there instead (only if the file exists) */
 function log(s) {
   try { var f = new File(LOG); if (!f.exists) return; f.lineFeed = "Unix"; f.open("e"); f.seek(0, 2); f.writeln(new Date().toTimeString().substr(0, 8) + " " + s); f.close(); } catch (e) {}
 }
 try {
  var VERSION = "@MINCOLOR_VERSION@";
  var CONFIG_NAME = "mincolor.ocio";
  var CONFIG_TEXT = @MINCOLOR_CONFIG_JS@;              /* ocio/mincolor.ocio, generated by tools/make_ocio */
  var UNMANAGED_NAME = "mincolor-unmanaged.ocio";
  var UNMANAGED_TEXT = @MINCOLOR_UNMANAGED_JS@;        /* ocio/mincolor-unmanaged.ocio: Fix OCIO's "Unmanaged" */
  var MN_OUTPUT = "ski.bialkow minColor Output";
  var MN_MACFIX = "ski.bialkow minColor macOS Fix";
  var MN_INPUT = "ski.bialkow minColor Input";
  var IN_JSON = @MINCOLOR_IN_JSON_JS@;                 /* the starter minColor/in.json */
  var IN_GAMUTS = @MINCOLOR_INPUT_GAMUTS@;             /* the Input's menus, in menu order (item k = value k + 1) */
  var IN_TRANSFERS = @MINCOLOR_INPUT_TRANSFERS@;
  var IN_RANGES = ["Full", "Limited (video)"];         /* kRangePopup in ae/common/drt_ae_params.h */
  var DISPLAYS = @MINCOLOR_DISPLAYS@;                  /* the Output's Display Encoding presets (menu item k + 2; 1 = Custom) */
  /* The working spaces Fix OCIO offers: the config's linear spaces, with the gamut each
     one is in the effects' menus. "working" is its item in the Input's Working Gamut
     menu (kWorkingGamutMap in ae/common/drt_ae_effect.mm: these are its first five,
     append-only, so stable); the Output's Input Gamut menu is IN_GAMUTS order.
     "Unmanaged" pins mincolor-unmanaged.ocio instead: a pass-through config whose working
     space "minColor Output" is a label; the Output encodes for the display, its
     macOS display corrects the viewer, and the panel leaves the effects'
     gamuts alone (gamut null). */
  var WORKING = [
    { ocio: "ACEScg",          gamut: "ACEScg",      working: 1 },
    { ocio: "ACES2065-1",      gamut: "ACES 2065-1", working: 2 },
    { ocio: "Linear Rec.709",  gamut: "Rec.709",     working: 3 },
    { ocio: "Linear P3-D65",   gamut: "P3-D65",      working: 4 },
    { ocio: "Linear Rec.2020", gamut: "Rec.2020",    working: 5 },
    { ocio: "Unmanaged",       gamut: null,          working: 0, ws: "minColor Output", unmanaged: true }
  ];

  var win;
  if (thisObj instanceof Panel) win = thisObj;
  else {
    try { if ($.global.__minColorAEWin) $.global.__minColorAEWin.close(); } catch (e) {}
    win = new Window("palette", "minColor", undefined, { resizeable: true });
    $.global.__minColorAEWin = win;   /* a DoScript-launched palette needs a reference to outlive the script */
  }
  /* Everything sits in one group, centred vertically in the dock; the report box has a
     fixed size, so changing text never moves the buttons. */
  win.orientation = "column"; win.alignChildren = ["fill", "center"]; win.spacing = 0; win.margins = 15;
  var body = win.add("group");
  body.orientation = "column"; body.alignChildren = ["fill", "top"]; body.alignment = ["fill", "center"]; body.spacing = 10;

  // ---- file helpers ------------------------------------------------------------
  function readText(file) {
    if (!file.exists) return null;
    file.encoding = "UTF-8";
    if (!file.open("r")) return null;
    var s = file.read(); file.close(); return s;
  }
  function writeText(file, s) {
    file.encoding = "UTF-8"; file.lineFeed = "Unix";
    if (!file.open("w")) return false;
    var ok = file.write(s); file.close(); return ok;
  }

  // ---- the .aep working-space record ---------------------------------------------------
  /* A .aep is RIFX (big-endian sizes, chunks padded to even). The project's working
     space is a top-level "PwCs" chunk followed by a "Utf8" chunk holding JSON, so a
     rewrite only changes that chunk and the RIFX header's size; the XMP trailer after
     the RIFX body is kept. The JSON is what AE 26.5 itself writes for a working
     space picked in Project Settings (read back from a saved project):
     colorProfileData is base64 of {"colorSpace1":"<name>"}. The technique
     (save, back up, rewrite, reopen) comes from minColor 0.x's AEPPatch. */
  var B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  function b64(s) {   /* ASCII in */
    var out = "", i = 0;
    while (i < s.length) {
      var a = s.charCodeAt(i++), b = i < s.length ? s.charCodeAt(i++) : NaN, c = i < s.length ? s.charCodeAt(i++) : NaN;
      var t = (a << 16) | ((isNaN(b) ? 0 : b) << 8) | (isNaN(c) ? 0 : c);
      out += B64.charAt((t >> 18) & 63) + B64.charAt((t >> 12) & 63) + (isNaN(b) ? "=" : B64.charAt((t >> 6) & 63)) + (isNaN(c) ? "=" : B64.charAt(t & 63));
    }
    return out;
  }
  function wsJSON(name) {
    return '{"baseColorProfile":{"colorProfileData":"' + b64('{"colorSpace1":"' + name + '"}') + '",' +
           '"colorProfileName":"' + name + '"},"baseProfileType":3}';
  }
  function u32(s, o) { return ((s.charCodeAt(o) << 24) | (s.charCodeAt(o + 1) << 16) | (s.charCodeAt(o + 2) << 8) | s.charCodeAt(o + 3)) >>> 0; }
  function p32(n) { return String.fromCharCode((n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, n & 255); }
  function readBinary(file) { file.encoding = "BINARY"; if (!file.open("r")) return null; var s = file.read(); file.close(); return s; }
  function writeBinary(file, s) { file.encoding = "BINARY"; if (!file.open("w")) return false; var ok = file.write(s); file.close(); return ok; }
  /* Returns null on success, else why it did not write. */
  function writeWorkingSpace(file, json) {
    var d = readBinary(file);
    if (d === null) return "could not read " + file.fsName;
    if (d.substr(0, 4) !== "RIFX") return "not a RIFX .aep";
    var total = 8 + u32(d, 4), off = 12, prev = null;
    while (off + 8 <= total) {
      var tag = d.substr(off, 4), sz = u32(d, off + 4), next = off + 8 + sz + (sz & 1);
      if (tag === "Utf8" && prev === "PwCs") {
        var chunk = "Utf8" + p32(json.length) + json + ((json.length & 1) ? "\x00" : "");
        d = d.substring(0, off) + chunk + d.substring(next);
        total += chunk.length - (next - off);
        d = "RIFX" + p32(total - 8) + d.substring(8);
        return writeBinary(file, d) ? null : "could not write " + file.fsName;
      }
      prev = tag; off = next;
    }
    return "no working-space record found";
  }

  /* minColor/project.json: the panel's record of the working space Fix OCIO set. */
  function workingFor(ocioName) { for (var i = 0; i < WORKING.length; i++) if (WORKING[i].ocio === ocioName) return WORKING[i]; return null; }
  function managedFor(ocioName) { var w = workingFor(ocioName); return (w && w.gamut) ? w : null; }   /* null for Unmanaged */
  function readProjectJSON() {
    var f = app.project.file;
    if (!f) return null;
    var jf = new File(f.parent.fsName + "/minColor/project.json");
    var d = jf.exists ? parseJSON(readText(jf)) : null;
    return (d && workingFor(d.working)) ? d : null;
  }
  function chooseWorking(current) {
    if ($.global.__minColorAETestWorking !== undefined) return $.global.__minColorAETestWorking;   /* unattended tests */
    var dlg = new Window("dialog", "minColor: Fix OCIO");
    dlg.orientation = "column"; dlg.alignChildren = ["fill", "top"]; dlg.margins = 14; dlg.spacing = 10;
    var t = dlg.add("statictext", undefined,
      "Saves this project, points its OCIO config at minColor/" + CONFIG_NAME + " with the working space below " +
      "(Unmanaged: the pass-through minColor/" + UNMANAGED_NAME + "), " +
      "and reopens it (undo history is cleared; a backup goes in minColor/). On an Adobe-engine project this " +
      "changes how footage is interpreted.", { multiline: true });
    t.preferredSize = [420, 64];
    var g = dlg.add("group"); g.add("statictext", undefined, "Working space:");
    var names = []; for (var i = 0; i < WORKING.length; i++) names.push(WORKING[i].ocio);
    var dd = g.add("dropdownlist", undefined, names); dd.selection = Math.max(0, indexOf(names, current));
    var b = dlg.add("group"); b.alignment = ["right", "bottom"];
    b.add("button", undefined, "Cancel", { name: "cancel" }); b.add("button", undefined, "Fix OCIO", { name: "ok" });
    return dlg.show() === 1 ? dd.selection.text : null;
  }

  /* Fix OCIO: the config into minColor/ (only when missing: AE caches a parsed config
     per path for the session, and the copy may have been edited), the project's OCIO
     config set to it with OCIO on (live, through scripting), saved, backed up to
     minColor/, the chosen working space written into the file, reopened, read back,
     and recorded in minColor/project.json. */
  function fixOCIO() {
    var out = [], f = app.project.file;
    if (!f) { out.push("Save the project first: the config goes in a minColor folder next to it. Nothing changed."); return out; }
    var prev = readProjectJSON();
    var name = chooseWorking(prev ? prev.working : "ACEScg");
    if (!name) { out.push("Cancelled. Nothing changed."); return out; }
    var dir = new Folder(f.parent.fsName + "/minColor");
    if (!dir.exists && !dir.create()) { out.push("Could not create " + dir.fsName + ". Nothing changed."); return out; }
    var W = workingFor(name), cfgName = W.unmanaged ? UNMANAGED_NAME : CONFIG_NAME, cfgText = W.unmanaged ? UNMANAGED_TEXT : CONFIG_TEXT;
    var wsName = W.ws || name;
    var cfg = new File(dir.fsName + "/" + cfgName);
    if (!cfg.exists) {
      if (!writeText(cfg, cfgText)) { out.push("Could not write " + cfg.fsName + ". Nothing changed."); return out; }
      out.push("Wrote minColor/" + cfgName + ".");
    } else if (readText(cfg) !== cfgText) {
      out.push("Kept minColor/" + cfgName + " (it differs from this panel's " + VERSION + "; delete it for a fresh copy).");
    }
    try {
      app.project.ocioConfigurationFile = cfg.fsName;
      if (app.project.colorManagementSystem !== 1) app.project.colorManagementSystem = 1;
    } catch (e) { out.push("After Effects refused the config: " + e.toString() + ". Project not saved."); return out; }
    var path = f.fsName;
    app.project.save();
    var backup = new File(dir.fsName + "/" + f.name.replace(/\.aep$/i, "") + ".before-fix-ocio.aep");
    if (!new File(path).copy(backup.fsName)) { out.push("Could not back up the project; the working space was not changed. Set it in Project Settings > Color."); return out; }
    var why = writeWorkingSpace(new File(path), wsJSON(wsName));
    if (why) { out.push("Working space not changed (" + why + "). Set it in Project Settings > Color."); return out; }
    app.open(new File(path));
    var ws = ""; try { ws = app.project.workingSpace; } catch (e) {}
    if (ws !== wsName) {
      out.push("Reopened, but the working space reads \"" + ws + "\". The previous file is minColor/" + backup.name.replace(/%20/g, " ") + ".");
      return out;
    }
    if (!writeText(new File(dir.fsName + "/project.json"), '{\n  "working": "' + name + '"\n}\n'))
      out.push("Could not write minColor/project.json; Apply In and Add Output will not follow the working space.");
    out.push("Fixed: OCIO config minColor/" + cfgName + ", working space " + wsName + (W.gamut ? "" : " (Unmanaged: the Output encodes for the display)") + ". Project reopened.");
    out.push("Backup: minColor/" + backup.name.replace(/%20/g, " "));
    if (prev && prev.working !== name) out.push("The working space changed from " + prev.working + ": press Apply In and check each minColor Output's Input Gamut.");
    return out;
  }

  // ---- In presets ---------------------------------------------------------------------
  function indexOf(a, v) { for (var i = 0; i < a.length; i++) if (a[i] === v) return i; return -1; }
  function parseJSON(text) { try { return eval("(" + text + ")"); } catch (e) { return null; } }   /* ExtendScript has no JSON */

  /* The rules: minColor/in.json next to the saved project (written from the starter when
     missing), the starter itself for an unsaved one. Each rule becomes
     {name, exts, g, t, r} with menu values; a rule naming an entry the Input lacks is
     dropped and reported. */
  function loadInRules(out) {
    var text = IN_JSON, where = "built-in rules (project not saved)", f = app.project.file;
    if (f) {
      var dir = new Folder(f.parent.fsName + "/minColor"), jf = new File(dir.fsName + "/in.json");
      if (!jf.exists) {
        if ((dir.exists || dir.create()) && writeText(jf, IN_JSON)) out.push("Wrote minColor/in.json (edit it to change the rules).");
        else out.push("Could not write minColor/in.json; using the built-in rules.");
      }
      if (jf.exists) { text = readText(jf); where = "minColor/in.json"; }
    }
    var d = parseJSON(text);
    if (!d || !(d.rules instanceof Array)) { out.push(where + " is not valid JSON with a \"rules\" list; nothing applied."); return null; }
    var rules = [];
    for (var i = 0; i < d.rules.length; i++) {
      var r = d.rules[i], label = r.name || ("rule " + (i + 1));
      var g = indexOf(IN_GAMUTS, r.gamut), t = indexOf(IN_TRANSFERS, r.transfer), rg = indexOf(IN_RANGES, r.range || "Full");
      if (g < 0 || t < 0 || rg < 0 || !(r.extensions instanceof Array)) {
        out.push("Skipped \"" + label + "\" in " + where + ": " + (g < 0 ? "unknown gamut \"" + r.gamut + "\"" :
                 (t < 0 ? "unknown transfer \"" + r.transfer + "\"" : (rg < 0 ? "unknown range \"" + r.range + "\"" : "no extensions list"))) + ".");
        continue;
      }
      var exts = {}; for (var k = 0; k < r.extensions.length; k++) exts[String(r.extensions[k]).toLowerCase().replace(/^\./, "")] = true;
      rules.push({ name: label, exts: exts, g: g + 1, t: t + 1, r: rg + 1 });
    }
    return { rules: rules, where: where };
  }
  function ruleFor(rules, ext) { for (var i = 0; i < rules.length; i++) if (rules[i].exts[ext]) return rules[i]; return null; }
  function footageExt(layer) {
    var src = null;
    try { src = layer.source; } catch (e) { return null; }   /* cameras, lights */
    if (!(src instanceof FootageItem) || !(src.mainSource instanceof FileSource) || !src.file) return null;
    var m = src.file.name.match(/\.([^.]+)$/);
    return m ? m[1].toLowerCase() : "";
  }
  function inputEffect(layer) {
    var parade = layer.property("ADBE Effect Parade");
    for (var i = 1; i <= parade.numProperties; i++) if (parade.property(i).matchName === MN_INPUT) return parade.property(i);
    return null;
  }

  /* Apply In: for each selected layer in the active comp whose source is a file, the
     first rule matching its extension sets minColor Input's Gamut, Transfer and Range,
     adding the effect first in the stack when the layer has none. Shows the plan, then
     applies it as one undo group. Reports every selected layer, changed or not. */
  function applyIn() {
    var out = notInstalled("minColor Input");
    if (out) return out;
    out = [];
    var comp = app.project.activeItem;
    if (!(comp instanceof CompItem)) { out.push("Open a comp and select footage layers first; nothing changed."); return out; }
    var sel = comp.selectedLayers;
    if (!sel.length) { out.push("Select footage layers in \"" + comp.name + "\" first; nothing changed."); return out; }
    var R = loadInRules(out);
    if (!R) return out;
    var P0 = readProjectJSON(), W = P0 ? managedFor(P0.working) : null;   /* null (none, or Unmanaged): leave Working Gamut alone */
    var plan = [], notes = [];
    for (var i = 0; i < sel.length; i++) {
      var l = sel[i], tag = l.index + " \"" + l.name + "\"", ext = footageExt(l);
      if (ext === null) { notes.push(tag + ": not file footage, skipped"); continue; }
      var rule = ruleFor(R.rules, ext);
      if (!rule) { notes.push(tag + ": no rule for ." + ext + ", skipped"); continue; }
      var fx = inputEffect(l), what = rule.name + ": " + IN_GAMUTS[rule.g - 1] + ", " + IN_TRANSFERS[rule.t - 1] + ", " + IN_RANGES[rule.r - 1] +
                                    (W ? " -> " + W.ocio : "");
      if (fx && fx.property("Input Gamut").value === rule.g && fx.property("Input Transfer").value === rule.t &&
          fx.property("Input Range").value === rule.r && (!W || fx.property("Working Gamut").value === W.working)) { notes.push(tag + ": already " + what); continue; }
      plan.push({ layer: l, rule: rule, add: !fx, line: tag + ": " + (fx ? "set " : "add Input, ") + what });
    }
    if (!plan.length) { out.push("Nothing to change (" + R.where + ")."); return out.concat(notes); }
    var lines = []; for (var j = 0; j < plan.length; j++) lines.push(plan[j].line);
    var shown = lines.length > 15 ? lines.slice(0, 15).concat(["... and " + (lines.length - 15) + " more"]) : lines;
    if (!$.global.__minColorAEAutoConfirm && !confirm("Apply In (" + R.where + "):\n\n" + shown.join("\n") + "\n\nApply?")) {
      out.push("Cancelled. Nothing changed."); return out;
    }
    app.beginUndoGroup("minColor: Apply In");
    var done = 0;
    try {
      for (var k = 0; k < plan.length; k++) {
        var P = plan[k], parade = P.layer.property("ADBE Effect Parade"), e;
        if (P.add) {
          parade.addProperty(MN_INPUT).moveTo(1);   /* moveTo invalidates the reference: fetch it again */
          e = parade.property(1);
        } else e = inputEffect(P.layer);
        e.property("Input Gamut").setValue(P.rule.g);
        e.property("Input Transfer").setValue(P.rule.t);
        e.property("Input Range").setValue(P.rule.r);
        if (W) e.property("Working Gamut").setValue(W.working);
        done++;
      }
    } catch (err) { out.push("Stopped after " + done + " of " + plan.length + ": " + err.toString()); }
    app.endUndoGroup();
    out.push("Applied to " + done + " layer" + (done === 1 ? "" : "s") + " (" + R.where + "):");
    return out.concat(lines.slice(0, done), notes);
  }

  // ---- In Rules dialog --------------------------------------------------------------
  /* Edits minColor/in.json as a table: one row per rule, the Input's own menu entries
     in the dropdowns, so a name can never be misspelt. Rows are rebuilt on add, remove
     and reorder (ScriptUI has no grid); a radio button marks the row those act on.
     Nothing is written until Save; Reset to defaults loads the starter rules into the
     table. Fields of in.json the table does not show (e.g. "about") are kept. */
  function jstr(v) { return '"' + String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"'; }
  function serializeRules(doc) {
    var L = ["{"], keys = [];
    for (var k in doc) if (doc.hasOwnProperty(k) && k !== "rules") keys.push(k);
    for (var a = 0; a < keys.length; a++) L.push("  " + jstr(keys[a]) + ": " + jstr(doc[keys[a]]) + ",");
    L.push('  "rules": [');
    for (var i = 0; i < doc.rules.length; i++) {
      var r = doc.rules[i], ex = [];
      for (var j = 0; j < r.extensions.length; j++) ex.push(jstr(r.extensions[j]));
      L.push("    {");
      L.push('      "name": ' + jstr(r.name) + ",");
      L.push('      "extensions": [' + ex.join(", ") + "],");
      L.push('      "gamut": ' + jstr(r.gamut) + ', "transfer": ' + jstr(r.transfer) + ', "range": ' + jstr(r.range));
      L.push("    }" + (i < doc.rules.length - 1 ? "," : ""));
    }
    L.push("  ]", "}", "");
    return L.join("\n");
  }
  function splitExts(text) {
    var parts = String(text).toLowerCase().split(/[\s,;]+/), out = [], seen = {};
    for (var i = 0; i < parts.length; i++) { var e = parts[i].replace(/^\*?\./, ""); if (e && !seen[e]) { seen[e] = true; out.push(e); } }
    return out;
  }
  /* Returns { doc, file, note } or { error }. */
  function loadRulesDoc() {
    var f = app.project.file;
    if (!f) return { error: "Save the project first: the rules live in a minColor folder next to it." };
    var jf = new File(f.parent.fsName + "/minColor/in.json"), note = "";
    var doc = jf.exists ? parseJSON(readText(jf)) : null;
    if (jf.exists && (!doc || !(doc.rules instanceof Array))) { doc = null; note = "minColor/in.json was not readable; showing the defaults (Save replaces it)."; }
    if (!doc) doc = parseJSON(IN_JSON);
    return { doc: doc, file: jf, note: note };
  }
  function editInRules() {
    var out = [], L = loadRulesDoc();
    if (L.error) { out.push(L.error + " Nothing changed."); return out; }
    var doc = L.doc, rows = [];
    function fromDoc(d) {
      rows = [];
      for (var i = 0; i < d.rules.length; i++) {
        var r = d.rules[i];
        rows.push({ name: String(r.name || ""), exts: (r.extensions instanceof Array ? r.extensions : []).join(" "),
                    g: indexOf(IN_GAMUTS, r.gamut), t: indexOf(IN_TRANSFERS, r.transfer), r: indexOf(IN_RANGES, r.range || "Full") });
      }
    }
    fromDoc(doc);
    var sel = rows.length ? 0 : -1;

    var dlg = new Window("dialog", "minColor In Rules", undefined, { resizeable: false });
    dlg.orientation = "column"; dlg.alignChildren = ["fill", "top"]; dlg.margins = 14; dlg.spacing = 8;
    var hint = dlg.add("statictext", undefined,
      "Apply In uses the first rule whose extensions match a footage layer's file. Saved to minColor/in.json.", { multiline: true });
    hint.preferredSize = [780, 18];
    if (L.note) dlg.add("statictext", undefined, L.note);
    var head = dlg.add("group"); head.spacing = 6;
    var W = { pick: 20, name: 210, exts: 200, g: 150, t: 170, r: 110 };
    function hcell(t, w) { var c = head.add("statictext", undefined, t); c.preferredSize = [w, 16]; }
    hcell("", W.pick); hcell("Rule", W.name); hcell("Extensions", W.exts); hcell("Gamut", W.g); hcell("Transfer", W.t); hcell("Range", W.r);
    var box = dlg.add("group"); box.orientation = "column"; box.alignChildren = ["fill", "top"]; box.spacing = 4;

    function readRows() {   /* controls -> rows */
      for (var i = 0; i < box.children.length; i++) {
        var c = box.children[i].children, R = rows[i];
        R.name = c[1].text; R.exts = c[2].text;
        R.g = c[3].selection ? c[3].selection.index : -1; R.t = c[4].selection ? c[4].selection.index : -1; R.r = c[5].selection ? c[5].selection.index : -1;
      }
    }
    function build() {   /* rows -> controls */
      while (box.children.length) box.remove(box.children[0]);
      for (var i = 0; i < rows.length; i++) {
        var R = rows[i], g = box.add("group"); g.spacing = 6;
        var rb = g.add("radiobutton"); rb.preferredSize = [W.pick, 20]; rb.value = (i === sel);
        (function (k) { rb.onClick = function () { readRows(); sel = k; for (var q = 0; q < box.children.length; q++) box.children[q].children[0].value = (q === k); }; })(i);
        var n = g.add("edittext", undefined, R.name); n.preferredSize = [W.name, 22];
        var e = g.add("edittext", undefined, R.exts); e.preferredSize = [W.exts, 22]; e.helpTip = "Space- or comma-separated, no dots: exr sxr";
        var dg = g.add("dropdownlist", undefined, IN_GAMUTS); dg.preferredSize = [W.g, 22]; if (R.g >= 0) dg.selection = R.g;
        var dt = g.add("dropdownlist", undefined, IN_TRANSFERS); dt.preferredSize = [W.t, 22]; if (R.t >= 0) dt.selection = R.t;
        var dr = g.add("dropdownlist", undefined, IN_RANGES); dr.preferredSize = [W.r, 22]; if (R.r >= 0) dr.selection = R.r;
      }
      dlg.layout.layout(true);
    }
    var bar = dlg.add("group"); bar.orientation = "row"; bar.alignment = ["fill", "bottom"];
    var left = bar.add("group"), right = bar.add("group"); right.alignment = ["right", "center"];
    var bAddR = left.add("button", undefined, "+ Add"), bDel = left.add("button", undefined, "\u2212 Remove"),
        bUp = left.add("button", undefined, "\u25B2"), bDn = left.add("button", undefined, "\u25BC");
    bUp.preferredSize = bDn.preferredSize = [36, 24];
    var bReset = right.add("button", undefined, "Reset to defaults"), bCancel = right.add("button", undefined, "Cancel", { name: "cancel" }),
        bSave = right.add("button", undefined, "Save", { name: "ok" });
    bAddR.onClick = function () { readRows(); rows.push({ name: "New rule", exts: "", g: indexOf(IN_GAMUTS, "Rec.709"), t: indexOf(IN_TRANSFERS, "sRGB"), r: 0 }); sel = rows.length - 1; build(); };
    bDel.onClick = function () { readRows(); if (sel < 0) return; rows.splice(sel, 1); sel = Math.min(sel, rows.length - 1); build(); };
    bUp.onClick = function () { readRows(); if (sel <= 0) return; var t = rows[sel - 1]; rows[sel - 1] = rows[sel]; rows[sel] = t; sel--; build(); };
    bDn.onClick = function () { readRows(); if (sel < 0 || sel >= rows.length - 1) return; var t = rows[sel + 1]; rows[sel + 1] = rows[sel]; rows[sel] = t; sel++; build(); };
    bReset.onClick = function () { fromDoc(parseJSON(IN_JSON)); sel = rows.length ? 0 : -1; build(); };
    var result = null;
    bSave.onClick = function () {
      readRows();
      var rules = [], problems = [];
      for (var i = 0; i < rows.length; i++) {
        var R = rows[i], ex = splitExts(R.exts), label = R.name || ("rule " + (i + 1));
        if (!ex.length) problems.push(label + ": no extensions");
        if (R.g < 0 || R.t < 0 || R.r < 0) problems.push(label + ": pick a gamut, transfer and range");
        rules.push({ name: R.name || ("Rule " + (i + 1)), extensions: ex, gamut: IN_GAMUTS[R.g], transfer: IN_TRANSFERS[R.t], range: IN_RANGES[R.r] });
      }
      if (problems.length) { alert("Not saved:\n" + problems.join("\n")); return; }
      doc.rules = rules; result = doc; dlg.close(1);
    };
    build();
    if ($.global.__minColorAETestDialog) { $.global.__minColorAETestDialog(dlg, { box: box, add: bAddR, del: bDel, up: bUp, down: bDn, reset: bReset, save: bSave }); }   /* unattended tests drive the controls */
    else dlg.show();
    if (!result) { out.push("In Rules: closed without saving."); return out; }
    var dir = L.file.parent;
    if (!dir.exists && !dir.create()) { out.push("Could not create " + dir.fsName + "; rules not saved."); return out; }
    if (!writeText(L.file, serializeRules(result))) { out.push("Could not write " + L.file.fsName + "; rules not saved."); return out; }
    out.push("Saved " + result.rules.length + " rule" + (result.rules.length === 1 ? "" : "s") + " to minColor/in.json.");
    var dup = {}, dups = [];
    for (var a = 0; a < result.rules.length; a++) for (var b = 0; b < result.rules[a].extensions.length; b++) {
      var x = result.rules[a].extensions[b]; if (dup[x] && indexOf(dups, x) < 0) dups.push(x); dup[x] = true;
    }
    if (dups.length) out.push("Note: ." + dups.join(", .") + (dups.length === 1 ? " is" : " are") + " in more than one rule; the first one wins.");
    return out;
  }

  /* Is the effect installed in this After Effects? Without it, addProperty() still
     succeeds when the project already holds instances of that effect (AE keeps them as
     placeholders, settings intact) and the panel would add placeholders that do nothing.
     The Effect menu entry is the fast, reliable test: findMenuCommandId is 0 when the
     effect did not load (iterating app.effects takes seconds). */
  function notInstalled(effectName) {
    return app.findMenuCommandId(effectName) === 0 ?
      [effectName + " is not installed in this After Effects (no Effect > minColor > " + effectName + "); nothing changed. " +
       "Layers that already carry it keep their settings and come back when it is installed."] : null;
  }

  // ---- layers ------------------------------------------------------------------------
  function hasEffect(layer, matchName) {
    var parade;
    try { parade = layer.property("ADBE Effect Parade"); } catch (e) { return false; }   /* cameras, lights */
    if (!parade) return false;
    for (var i = 1; i <= parade.numProperties; i++) if (parade.property(i).matchName === matchName) return true;
    return false;
  }
  function findLayers(comp, matchName) {
    var hits = [];
    for (var i = 1; i <= comp.numLayers; i++) if (hasEffect(comp.layer(i), matchName)) hits.push(comp.layer(i));
    return hits;
  }

  /* Add Output: an adjustment layer at the top of the active comp carrying minColor
     Output at its defaults; below a macOS Fix layer if the comp has one (the Fix
     re-encodes the Output's pixels, so it must stay above). One Output per comp: an
     existing one is reported, not duplicated. */
  function addOutput() {
    var out = notInstalled("minColor Output");
    if (out) return out;
    out = [];
    var comp = app.project.activeItem;
    if (!(comp instanceof CompItem)) { out.push("Open or select a comp first; nothing added."); return out; }
    var existing = findLayers(comp, MN_OUTPUT);
    if (existing.length) {
      out.push("\"" + comp.name + "\" already has minColor Output on layer " + existing[0].index +
               " (\"" + existing[0].name + "\"); nothing added.");
      return out;
    }
    var fixes = findLayers(comp, MN_MACFIX);
    app.beginUndoGroup("minColor: Add Output");
    try {
      var l = comp.layers.addSolid([1, 1, 1], "minColor Output", comp.width, comp.height, comp.pixelAspect, comp.duration);
      l.adjustmentLayer = true;
      var fx = l.property("ADBE Effect Parade").addProperty(MN_OUTPUT);
      /* In a project Fix OCIO set up, the comp is the working space and OCIO encodes:
         the Output reads that gamut and hands back linear light in it. The preset popup
         writes Display Gamut, EOTF, peak and clamp the way picking it by hand does. */
      var P0 = readProjectJSON(), W = P0 ? managedFor(P0.working) : null, lin = indexOf(DISPLAYS, "None - Linear / Working Gamut");
      if (W && lin >= 0) {
        fx.property("Input Gamut").setValue(indexOf(IN_GAMUTS, W.gamut) + 1);
        fx.property("Display Encoding").setValue(lin + 2);
      }
      if (fixes.length) l.moveAfter(fixes[fixes.length - 1]);   /* below the lowest Fix layer */
      out.push("Added minColor Output to \"" + comp.name + "\" on layer " + l.index +
               (fixes.length ? ", under the macOS Fix layer" : ", at the top") +
               (W ? ", in and out in " + W.ocio + " (linear)." : "."));
    } catch (e) {
      out.push("Add Output failed: " + e.toString());
    }
    app.endUndoGroup();
    return out;
  }

  // ---- UI ----------------------------------------------------------------------------
  /* Stock ScriptUI only (owner-drawn pills and glyphs glitched in AE's dock): two titled
     panels of plain buttons, a fixed-size report box, the version. */
  function section(title) {
    var p = body.add("panel", undefined, title);
    p.orientation = "column"; p.alignChildren = ["fill", "top"]; p.spacing = 6; p.margins = [10, 15, 10, 10];
    return p;
  }
  function button(parent, label, tip) {
    var b = parent.add("button", undefined, label);
    if (tip) b.helpTip = tip;
    return b;
  }

  var pProject = section("Project");
  var bFix = button(pProject, "Fix OCIO",
    "Saves the project, sets its OCIO config to minColor/mincolor.ocio with the working space you\n" +
    "choose (or Unmanaged), and reopens it (a backup goes in minColor/; undo history is cleared).\n" +
    "Turns OCIO on: on an Adobe-engine project that changes how footage is interpreted.\n" +
    "Press again after moving the project.");
  var bRules = button(pProject, "In Rules\u2026",
    "Edit this project's In rules (minColor/in.json): which Input settings each file extension gets");
  var pLayers = section("Layers");
  var bIn = button(pLayers, "Apply In",
    "Sets minColor Input on the selected footage layers from minColor/in.json, by file extension\n" +
    "(adds the effect first in the stack where missing). Shows the changes before applying.");
  var bAdd = button(pLayers, "Add Output",
    "Adjustment layer with minColor Output at the top of the active comp (under a macOS Fix layer if there is one)");
  var report = body.add("statictext", undefined, "", { multiline: true });
  report.preferredSize = [240, 60];
  body.add("statictext", undefined, "minColor " + VERSION);

  function run(fn) {
    var lines;
    try { lines = fn(); } catch (e) { lines = ["Error: " + e.toString() + " (line " + e.line + ")"]; log("ERR " + e.toString() + " line " + e.line); }
    report.text = lines.join("\n");
    log(lines.join(" | "));
    try { win.update(); } catch (e) {}
  }
  bIn.onClick = function () { run(applyIn); };
  bRules.onClick = function () { run(editInRules); };
  bAdd.onClick = function () { run(addOutput); };
  bFix.onClick = function () { run(fixOCIO); };

  win.__mc = { applyIn: bIn, inRules: bRules, addOutput: bAdd, fixOCIO: bFix, report: report };   /* for unattended tests */
  win.layout.layout(true);
  win.onResizing = win.onResize = function () { try { this.layout.resize(); } catch (e) {} };
  if (win instanceof Window) { win.center(); win.show(); }
 } catch (eTop) { log("LOAD " + eTop.toString() + " line " + eTop.line); }
})(this);
