// SPDX-License-Identifier: GPL-3.0-only
// minColorAE. Copyright (C) 2026 cbkow. Part of a work derived from OpenDRT v1.1.0 by Jed Smith (GPLv3); see NOTICE.
//
// make_ocio [out.ocio]: writes the minColor OCIO config (ocio/mincolor.ocio).
//
// Every gamut matrix comes from the core (drt_gamut_to_xyz, the same matrices
// minColor Input converts with), so a conversion made by the Input and one made
// by After Effects' OCIO agree by construction, including how the ACES spaces'
// D60 white reaches D65 (the core folds a CAT02 adaptation into AP0 and AP1).
// The scene reference is CIE XYZ D65.
//
// The config is a linear-conversion config, no rendering:
//   - five linear working spaces (ACEScg, ACES2065-1, Linear Rec.709, Linear
//     P3-D65, Linear Rec.2020), also offered as Output Module deliveries;
//   - two encoded spaces for delivery and viewing: sRGB (IEC 61966-2-1, the
//     piecewise curve) and Rec.709 BT.1886 (2.4 power);
//   - one view, "Un-tone-mapped", on three displays: sRGB, Rec.709 (BT.1886) and
//     macOS (AE viewport fix). The macOS display is viewer-only and never a
//     delivery: AE's viewport on macOS is Display P3 decoded as a 2.2 power, so
//     that view sends linear P3-D65 encoded 2.2 (what the earlier viewport shim
//     and the minColor macOS Fix effect do to the Output's sRGB codes);
//   - no file rules beyond Default, and the default role is Raw (data), so AE
//     never converts footage on import: minColor Input interprets media.
// Display, view and colour space names are project state in AE (stored by name):
// never rename them, only add.
//
// Curves keep the sign of negative values (negative_style: mirror), as minColor
// Input's decodes do.

#include <cstdio>
#include <string>

#include "opendrt.h"

namespace {

struct Linear { const char *name; int gamut; const char *desc; };
const Linear kLinear[] = {
    { "ACEScg",          DRT_IN_AP1,     "ACES AP1 primaries, linear. minColor's default working space." },
    { "ACES2065-1",      DRT_IN_AP0,     "ACES AP0 primaries, linear (the ACES interchange space)." },
    { "Linear Rec.709",  DRT_IN_REC709,  "Rec.709 / sRGB primaries, D65, linear." },
    { "Linear P3-D65",   DRT_IN_P3D65,   "Display P3 / P3-D65 primaries, linear." },
    { "Linear Rec.2020", DRT_IN_REC2020, "Rec.2020 primaries, D65, linear." },
};

void matrix(std::FILE *o, const char *indent, const drt::drt_mat3 &m, const char *dir)
{
    std::fprintf(o, "%s- !<MatrixTransform> {matrix: [%.10g, %.10g, %.10g, 0, %.10g, %.10g, %.10g, 0, %.10g, %.10g, %.10g, 0, 0, 0, 0, 1]%s}\n",
                 indent, m.x.x, m.x.y, m.x.z, m.y.x, m.y.y, m.y.z, m.z.x, m.z.y, m.z.z, dir);
}

void header(std::FILE *o, const char *name, const char *desc, bool data = false)   /* desc: no double quotes */
{
    std::fprintf(o, "  - !<ColorSpace>\n    name: %s\n    family: \"\"\n    bitdepth: 32f\n"
                    "    description: \"%s\"\n    isdata: %s\n", name, desc, data ? "true" : "false");
}

} // namespace

int main(int argc, char **argv)
{
    const char *path = argc > 1 ? argv[1] : "mincolor.ocio";
    std::FILE *o = std::fopen(path, "w");
    if (!o) { std::perror(path); return 1; }

    const drt::drt_mat3 rec709 = drt::drt_gamut_to_xyz(DRT_IN_REC709);
    const drt::drt_mat3 p3d65  = drt::drt_gamut_to_xyz(DRT_IN_P3D65);

    std::fprintf(o,
        "ocio_profile_version: 2.1\n"
        "\n"
        "# SPDX-License-Identifier: GPL-3.0-only\n"
        "# minColorAE. Copyright (C) 2026 cbkow. Part of a work derived from OpenDRT v1.1.0 by Jed Smith (GPLv3); see NOTICE.\n"
        "#\n"
        "# GENERATED by tools/make_ocio.cpp from the minColor core; do not edit by hand.\n"
        "# Linear colour conversions for After Effects, no rendering: five linear\n"
        "# working spaces, sRGB and Rec.709 BT.1886 for delivery and viewing, and one\n"
        "# view, Un-tone-mapped. The macOS display is viewer-only (AE's macOS viewport is\n"
        "# Display P3 decoded as a 2.2 power) and never a delivery. No file rules: AE does\n"
        "# not convert footage; minColor Input interprets media.\n"
        "\n"
        "name: minColor\n"
        "description: minColor linear conversions (no rendering). Generated by minColorAE tools/make_ocio.\n"
        "\n"
        "roles:\n"
        "  aces_interchange: ACES2065-1\n"
        "  cie_xyz_d65_interchange: CIE-XYZ-D65\n"
        "  scene_linear: ACEScg\n"
        "  rendering: ACEScg\n"
        "  compositing_linear: ACEScg\n"
        "  color_picking: sRGB\n"
        "  default: Raw\n"
        "  data: Raw\n"
        "\n"
        "file_rules:\n"
        "  - !<Rule> {name: Default, colorspace: default}\n"
        "\n"
        "displays:\n"
        "  macOS (AE viewport fix):\n"
        "    - !<View> {name: Un-tone-mapped, colorspace: macOS viewport}\n"
        "  sRGB:\n"
        "    - !<View> {name: Un-tone-mapped, colorspace: sRGB}\n"
        "  Rec.709 (BT.1886):\n"
        "    - !<View> {name: Un-tone-mapped, colorspace: Rec.709 BT.1886}\n"
        "\n"
        "active_displays: [macOS (AE viewport fix), sRGB, Rec.709 (BT.1886)]\n"
        "active_views: [Un-tone-mapped]\n"
        "# used by roles and views, kept out of AE's colour space menus\n"
        "inactive_colorspaces: [CIE-XYZ-D65, macOS viewport]\n"
        "\n"
        "colorspaces:\n");

    for (const Linear &l : kLinear) {
        header(o, l.name, l.desc);
        std::fprintf(o, "    to_scene_reference: !<GroupTransform>\n      children:\n");
        matrix(o, "        ", drt::drt_gamut_to_xyz(l.gamut), "");
        std::fprintf(o, "\n");
    }

    header(o, "sRGB", "sRGB (IEC 61966-2-1): Rec.709 primaries, the piecewise sRGB curve. For delivery and viewing.");
    std::fprintf(o, "    to_scene_reference: !<GroupTransform>\n      children:\n"
                    "        - !<ExponentWithLinearTransform> {gamma: [2.4, 2.4, 2.4, 1], offset: [0.055, 0.055, 0.055, 0], style: mirror}\n");
    matrix(o, "        ", rec709, "");
    std::fprintf(o, "\n");

    header(o, "Rec.709 BT.1886", "Rec.709 primaries, BT.1886 (2.4 power). For delivery and viewing.");
    std::fprintf(o, "    to_scene_reference: !<GroupTransform>\n      children:\n"
                    "        - !<ExponentTransform> {value: [2.4, 2.4, 2.4, 1], style: mirror}\n");
    matrix(o, "        ", rec709, "");
    std::fprintf(o, "\n");

    header(o, "CIE-XYZ-D65", "CIE XYZ, D65, linear: the scene reference.");
    std::fprintf(o, "\n");

    header(o, "macOS viewport", "Viewer only: linear P3-D65 encoded as a 2.2 power, for AE's Display P3 viewport on macOS. Never a delivery.");
    std::fprintf(o, "    to_scene_reference: !<GroupTransform>\n      children:\n"
                    "        - !<ExponentTransform> {value: [2.2, 2.2, 2.2, 1], style: mirror}\n");
    matrix(o, "        ", p3d65, "");
    std::fprintf(o, "\n");

    header(o, "Raw", "No transform. The default role: AE does not convert footage, minColor Input does.", true);

    std::fclose(o);
    std::printf("wrote %s\n", path);
    return 0;
}
